### ISSUE TITLE
Image link doesn't work

### ISSUE THREAD

**Issue by Userr017** [CheckoutFinland/plugin-magento2#1]
Module checkout main logo image link doesn't work so it doesn't display image.

Link: https://www.checkout.fi/wp-content/uploads/checkout-logo-pysty-RGB.png

`app/code/Op/Checkout/view/frontend/web/template/payment/checkout-bypass.html`

**Comment by Ahtoranta** [comment]
Fixed on https://github.com/CheckoutFinland/plugin-magento2/pull/2
